<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MAMATHA" failures="1" tests="11" name="com.CambriaProject.qa.testcases.LoginTest" time="167.482" errors="0" timestamp="2023-04-27T19:14:14 IST" skipped="0">
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Invalid_Character__Email_ID_Data" time="13.697"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_Email_ID_without_domain_name_or_without_com_Extention" time="16.630"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_without_Email_ID" time="14.887"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Valid_Email_ID" time="14.345"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Invalid_Password_Data" time="14.264"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_INValid_Password_Different_User" time="15.060"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_Valid_Password_Invalid_Email_ID" time="16.135"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_emptyData_Password" time="13.156"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="LogOut_Functionality" time="12.491"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Seeting_button_Functionality" time="15.449"/>
  <system-out/>
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Seeting_Page_Preload_Data" time="21.368">
    <failure message="expected [mamatha@facileconsulting.com] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [mamatha@facileconsulting.com] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.CambriaProject.qa.testcases.LoginTest.Seeting_Page_Preload_Data(LoginTest.java:167)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Seeting_Page_Preload_Data -->
  <system-out/>
</testsuite> <!-- com.CambriaProject.qa.testcases.LoginTest -->
